---
# GitHub Dependabot configuration for automated dependency updates
version: 2
updates:
  # Monitor GitHub Actions workflows
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
    open-pull-requests-limit: 5
    reviewers:
      - samccann
    commit-message:
      prefix: "chore"
      include: "scope"

  # Monitor Python dependencies in test requirements
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
    open-pull-requests-limit: 5
    reviewers:
      - samccann
    commit-message:
      prefix: "chore"
      include: "scope"
